### PR TITLE
Update resource admin

### PR DESCRIPTION
**Pull request by tannguyenvn007**
@nhanhvasnet  Please check "Update resource admin" for me

### CODE REVIEW

**Comment by vuongnd** [comment]
1 commit which include 258 file changed 🗡 
Kill me pls. 🔫

**Comment by tannguyenvn007** [comment]
That files was created when I requirded admin panel

**Comment by vuongnd** [comment]
The pushing them is neccessary?

**Comment by tannguyenvn007** [comment]
I think it not neccsesary

**Comment by vuongnd** [comment]
Hope it work and don't break anything. ;)

**Pull request merged**
